# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package
permissions:
  contents: write
  packages: write

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          - name: ubuntu-latest
            origfilename: scaffold
            filename: scaffold-lin
          - name: macos-latest
            origfilename: scaffold
            filename: scaffold-mac
          - name: windows-latest
            origfilename: scaffold.exe
            filename: scaffold-win.exe
    runs-on: ${{ matrix.os.name }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'graalvm'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    # TODO: could separate this into a different step but need to upload/download artifact of the JAR
    # to then process with native-image on each platform, would require moving away from using maven
    # for builting the native-images and config for that step. 
    - name: Build Assembled JAR with Maven
      id: maven_build
      run: mvn -B clean package --file pom.xml

    - name: Clean and Rebuild Metadata (for Native build)
      run: ./gh-scripts/cleanAndCreateMetadata.sh

    - name: Build `native-image` with Maven
      id: maven_build
      run: mvn -B -Pnative package --file pom.xml

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os.name }}-bin
        path: ./target/${{ matrix.os.origfilename }}
        retention-days: 5


  create_release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs: [build]
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v4
      with:
        path: path/to/artifacts

    - name: Display structure of downloaded files
      run: ls -R path/to/artifacts

    - name: Upload Linux Release Asset
      id: linux-release-asset 
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: path/to/artifacts/ubuntu-latest-bin/scaffold
        asset_name: scaffold_lin
        asset_content_type: application/exe

    - name: Upload Windows Release Asset
      id: windows-release-asset 
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: path/to/artifacts/windows-latest-bin/scaffold.exe
        asset_name: scaffold_win.exe
        asset_content_type: application/exe

    - name: Upload Mac Release Asset
      id: macos-release-asset 
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: path/to/artifacts/macos-latest-bin/scaffold
        asset_name: scaffold_mac
        asset_content_type: application/exe

    # - name: Publish to GitHub Packages Apache Maven
    #   run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
    #   env:
        GITHUB_TOKEN: ${{ github.token }}
